/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';


export namespace Components {

  interface AppAbout {}
  interface AppAboutAttributes extends StencilHTMLAttributes {}

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppSpeakers {}
  interface AppSpeakersAttributes extends StencilHTMLAttributes {}

  interface AppSponsors {}
  interface AppSponsorsAttributes extends StencilHTMLAttributes {}

  interface CmpAddress {
    'city': string;
    'name': string;
    'state': string;
    'street': string;
    'zip': string;
  }
  interface CmpAddressAttributes extends StencilHTMLAttributes {
    'city'?: string;
    'name'?: string;
    'state'?: string;
    'street'?: string;
    'zip'?: string;
  }

  interface CmpHeader {}
  interface CmpHeaderAttributes extends StencilHTMLAttributes {}

  interface CmpImageGrid {}
  interface CmpImageGridAttributes extends StencilHTMLAttributes {}

  interface CmpImage {
    /**
    * Alt Text for the Image
    */
    'alt': string;
    /**
    * Image directory.
    */
    'imgDirectory': string;
    /**
    * Transition to Large Screen Size.
    */
    'largePxl': number;
    /**
    * Responsive Full resolution image
    */
    'largeSrc': string;
    /**
    * Transition to Medium Screen Size.
    */
    'mediumPxl': number;
    /**
    * Responsive Medium sized image to be displayed on tablet sized screens
    */
    'mediumSrc': string;
    /**
    * Transition to Small Screen Size.
    */
    'smallPxl': number;
    /**
    * Responsive Small image to be displayed on phone sized screens
    */
    'smallSrc': string;
    /**
    * Name of the image to display
    */
    'src': string;
  }
  interface CmpImageAttributes extends StencilHTMLAttributes {
    /**
    * Alt Text for the Image
    */
    'alt': string;
    /**
    * Image directory.
    */
    'imgDirectory'?: string;
    /**
    * Transition to Large Screen Size.
    */
    'largePxl'?: number;
    /**
    * Responsive Full resolution image
    */
    'largeSrc'?: string;
    /**
    * Transition to Medium Screen Size.
    */
    'mediumPxl'?: number;
    /**
    * Responsive Medium sized image to be displayed on tablet sized screens
    */
    'mediumSrc'?: string;
    /**
    * Transition to Small Screen Size.
    */
    'smallPxl'?: number;
    /**
    * Responsive Small image to be displayed on phone sized screens
    */
    'smallSrc'?: string;
    /**
    * Name of the image to display
    */
    'src': string;
  }

  interface CmpMenuLinks {}
  interface CmpMenuLinksAttributes extends StencilHTMLAttributes {
    'onToggleMenuEvent'?: (event: CustomEvent) => void;
  }

  interface CmpMenu {}
  interface CmpMenuAttributes extends StencilHTMLAttributes {
    'onToggleMenuEvent'?: (event: CustomEvent) => void;
  }

  interface CmpMobileMenu {}
  interface CmpMobileMenuAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppAbout': Components.AppAbout;
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
    'AppSpeakers': Components.AppSpeakers;
    'AppSponsors': Components.AppSponsors;
    'CmpAddress': Components.CmpAddress;
    'CmpHeader': Components.CmpHeader;
    'CmpImageGrid': Components.CmpImageGrid;
    'CmpImage': Components.CmpImage;
    'CmpMenuLinks': Components.CmpMenuLinks;
    'CmpMenu': Components.CmpMenu;
    'CmpMobileMenu': Components.CmpMobileMenu;
  }

  interface StencilIntrinsicElements {
    'app-about': Components.AppAboutAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
    'app-speakers': Components.AppSpeakersAttributes;
    'app-sponsors': Components.AppSponsorsAttributes;
    'cmp-address': Components.CmpAddressAttributes;
    'cmp-header': Components.CmpHeaderAttributes;
    'cmp-image-grid': Components.CmpImageGridAttributes;
    'cmp-image': Components.CmpImageAttributes;
    'cmp-menu-links': Components.CmpMenuLinksAttributes;
    'cmp-menu': Components.CmpMenuAttributes;
    'cmp-mobile-menu': Components.CmpMobileMenuAttributes;
  }


  interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {}
  var HTMLAppAboutElement: {
    prototype: HTMLAppAboutElement;
    new (): HTMLAppAboutElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSpeakersElement extends Components.AppSpeakers, HTMLStencilElement {}
  var HTMLAppSpeakersElement: {
    prototype: HTMLAppSpeakersElement;
    new (): HTMLAppSpeakersElement;
  };

  interface HTMLAppSponsorsElement extends Components.AppSponsors, HTMLStencilElement {}
  var HTMLAppSponsorsElement: {
    prototype: HTMLAppSponsorsElement;
    new (): HTMLAppSponsorsElement;
  };

  interface HTMLCmpAddressElement extends Components.CmpAddress, HTMLStencilElement {}
  var HTMLCmpAddressElement: {
    prototype: HTMLCmpAddressElement;
    new (): HTMLCmpAddressElement;
  };

  interface HTMLCmpHeaderElement extends Components.CmpHeader, HTMLStencilElement {}
  var HTMLCmpHeaderElement: {
    prototype: HTMLCmpHeaderElement;
    new (): HTMLCmpHeaderElement;
  };

  interface HTMLCmpImageGridElement extends Components.CmpImageGrid, HTMLStencilElement {}
  var HTMLCmpImageGridElement: {
    prototype: HTMLCmpImageGridElement;
    new (): HTMLCmpImageGridElement;
  };

  interface HTMLCmpImageElement extends Components.CmpImage, HTMLStencilElement {}
  var HTMLCmpImageElement: {
    prototype: HTMLCmpImageElement;
    new (): HTMLCmpImageElement;
  };

  interface HTMLCmpMenuLinksElement extends Components.CmpMenuLinks, HTMLStencilElement {}
  var HTMLCmpMenuLinksElement: {
    prototype: HTMLCmpMenuLinksElement;
    new (): HTMLCmpMenuLinksElement;
  };

  interface HTMLCmpMenuElement extends Components.CmpMenu, HTMLStencilElement {}
  var HTMLCmpMenuElement: {
    prototype: HTMLCmpMenuElement;
    new (): HTMLCmpMenuElement;
  };

  interface HTMLCmpMobileMenuElement extends Components.CmpMobileMenu, HTMLStencilElement {}
  var HTMLCmpMobileMenuElement: {
    prototype: HTMLCmpMobileMenuElement;
    new (): HTMLCmpMobileMenuElement;
  };

  interface HTMLElementTagNameMap {
    'app-about': HTMLAppAboutElement
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
    'app-speakers': HTMLAppSpeakersElement
    'app-sponsors': HTMLAppSponsorsElement
    'cmp-address': HTMLCmpAddressElement
    'cmp-header': HTMLCmpHeaderElement
    'cmp-image-grid': HTMLCmpImageGridElement
    'cmp-image': HTMLCmpImageElement
    'cmp-menu-links': HTMLCmpMenuLinksElement
    'cmp-menu': HTMLCmpMenuElement
    'cmp-mobile-menu': HTMLCmpMobileMenuElement
  }

  interface ElementTagNameMap {
    'app-about': HTMLAppAboutElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'app-speakers': HTMLAppSpeakersElement;
    'app-sponsors': HTMLAppSponsorsElement;
    'cmp-address': HTMLCmpAddressElement;
    'cmp-header': HTMLCmpHeaderElement;
    'cmp-image-grid': HTMLCmpImageGridElement;
    'cmp-image': HTMLCmpImageElement;
    'cmp-menu-links': HTMLCmpMenuLinksElement;
    'cmp-menu': HTMLCmpMenuElement;
    'cmp-mobile-menu': HTMLCmpMobileMenuElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
